#ifndef EXT_FOCUSPHP_ROUTER_NOT_FOUND_ROUTER_H_
#define EXT_FOCUSPHP_ROUTER_NOT_FOUND_ROUTER_H_

extern zend_class_entry *focusphp_router_not_found_router_ce;

FOCUS_STARTUP_FUNCTION(not_found_router);

#endif